mode = "light"

accent = "#31638c"
selection = "#c8cccc"
muted = "#857863"

background = "#f2eade"
dark_background = "#e9e0d2"
darker_background = "#ddd3c3"
lighter_background = "#e7dbc6"

foreground = "#29231b"
dark_foreground = "#6b5f4c"
light_foreground = "#464038"
bright_foreground = "#080503"

hyprland_active_border = "rgba(31638cee) rgba(9b4f3dee) 45deg"
hyprland_inactive_border = "rgba(857863aa)"

red = "#9b4f3d"
yellow = "#6b4a01"
orange = "#854b18"
green = "#386442"
cyan = "#205f63"
blue = "#31638c"
magenta = "#865367"
brown = "#43260c"

bright_red = "#8f4533"
bright_yellow = "#614300"
bright_green = "#305b3a"
bright_cyan = "#16575a"
bright_blue = "#285981"
bright_magenta = "#7c495d"
