mode = "light"

accent = "#5a6a02"
selection = "#d4d7b5"
muted = "#83816a"

background = "#f7f6e8"
dark_background = "#edecdc"
darker_background = "#e0dfcd"
lighter_background = "#e9e8d0"

foreground = "#2c2b1d"
dark_foreground = "#696853"
light_foreground = "#48483a"
bright_foreground = "#14140a"

hyprland_active_border = "rgba(5a6a02ee) rgba(af4659ee) 45deg"
hyprland_inactive_border = "rgba(83816aaa)"

red = "#af4659"
yellow = "#6c4f20"
orange = "#914b29"
green = "#366821"
cyan = "#3e5e3f"
blue = "#5a6a02"
magenta = "#914f7d"
brown = "#492615"

bright_red = "#9e344a"
bright_yellow = "#523d1c"
bright_green = "#2b4f1e"
bright_cyan = "#314832"
bright_blue = "#45510f"
bright_magenta = "#82406e"
