mode = "light"

accent = "#2f7442"
selection = "#c4d9c9"
muted = "#748376"

background = "#eef6ef"
dark_background = "#e3ece5"
darker_background = "#d6dfd7"
lighter_background = "#dbe9dd"

foreground = "#202d22"
dark_foreground = "#5b6a5d"
light_foreground = "#3c4a3e"
bright_foreground = "#0b140d"

hyprland_active_border = "rgba(2f7442ee) rgba(c03710ee) 45deg"
hyprland_inactive_border = "rgba(748376aa)"

red = "#c03710"
yellow = "#545601"
orange = "#805300"
green = "#29671a"
cyan = "#22624d"
blue = "#2f7442"
magenta = "#9e4674"
brown = "#402a00"

bright_red = "#a92901"
bright_yellow = "#514200"
bright_green = "#234e19"
bright_cyan = "#1f4b3c"
bright_blue = "#275733"
bright_magenta = "#8e3665"
