mode = "dark"

accent = "#589bcb"
selection = "#1b354d"
muted = "#526d88"

background = "#030e1c"
dark_background = "#020b15"
darker_background = "#02070e"
lighter_background = "#041a30"

foreground = "#c6d2d7"
dark_foreground = "#6b849e"
light_foreground = "#a6b0b5"
bright_foreground = "#e8eef1"

hyprland_active_border = "rgba(ea5a55ee) rgba(40b865ee) 45deg"
hyprland_inactive_border = "rgba(526d88aa)"

red = "#ea5a55"
yellow = "#deb049"
orange = "#ef8837"
green = "#40b865"
cyan = "#66b8bc"
blue = "#589bcb"
magenta = "#ae7fb9"
brown = "#78441c"

bright_red = "#ff7e77"
bright_yellow = "#edc56c"
bright_green = "#69cd82"
bright_cyan = "#85ccd0"
bright_blue = "#78b4e1"
bright_magenta = "#c69ad0"
