mode = "light"

accent = "#a24703"
selection = "#e2cdc1"
muted = "#827d8b"

background = "#f4f3f6"
dark_background = "#eae9ed"
darker_background = "#dddbe0"
lighter_background = "#e5e3eb"

foreground = "#2b2830"
dark_foreground = "#686471"
light_foreground = "#48454d"
bright_foreground = "#121116"

hyprland_active_border = "rgba(a24703ee) rgba(b13f56ee) 45deg"
hyprland_inactive_border = "rgba(827d8baa)"

red = "#b13f56"
yellow = "#6f4c00"
orange = "#9a410e"
green = "#416701"
cyan = "#046251"
blue = "#a24703"
magenta = "#9c4573"
brown = "#4d2107"

bright_red = "#843241"
bright_yellow = "#573a00"
bright_green = "#334e0c"
bright_cyan = "#0e4b3f"
bright_blue = "#793810"
bright_magenta = "#753656"
