mode = "dark"

accent = "#95975c"
selection = "#393921"
muted = "#706f56"

background = "#15140a"
dark_background = "#100f08"
darker_background = "#0b0a05"
lighter_background = "#23210f"

foreground = "#d8d5c2"
dark_foreground = "#88866e"
light_foreground = "#b6b3a3"
bright_foreground = "#f4f3e9"

hyprland_active_border = "rgba(95975cee) rgba(bd7b63ee) 45deg"
hyprland_inactive_border = "rgba(706f56aa)"

red = "#bd7b63"
yellow = "#c6b77b"
orange = "#c89b6a"
green = "#94af79"
cyan = "#a1b7a4"
blue = "#95975c"
magenta = "#ae8999"
brown = "#644e35"

bright_red = "#cf8c74"
bright_yellow = "#d3c488"
bright_green = "#a2bd87"
bright_cyan = "#aec4b1"
bright_blue = "#a5a76b"
bright_magenta = "#be99a9"
