mode = "dark"

accent = "#dc739f"
selection = "#502735"
muted = "#866266"

background = "#1a0a0c"
dark_background = "#140809"
darker_background = "#0d0506"
lighter_background = "#2d1217"

foreground = "#d6d1bb"
dark_foreground = "#9d797d"
light_foreground = "#b4b09d"
bright_foreground = "#f0eee2"

hyprland_active_border = "rgba(dc739fee) rgba(d3b63bee) 45deg"
hyprland_inactive_border = "rgba(866266aa)"

red = "#de5e68"
yellow = "#d3b63b"
orange = "#eb8a39"
green = "#87a965"
cyan = "#c2ae7c"
blue = "#dc739f"
magenta = "#c477ae"
brown = "#76451d"

bright_red = "#f58086"
bright_yellow = "#e5ca63"
bright_green = "#a1c082"
bright_cyan = "#d5c396"
bright_blue = "#f190b7"
bright_magenta = "#db93c6"
