mode = "dark"

accent = "#f07e06"
selection = "#543310"
muted = "#736f63"

background = "#171614"
dark_background = "#11110f"
darker_background = "#0c0b0a"
lighter_background = "#25231e"

foreground = "#d8d7d4"
dark_foreground = "#8b877a"
light_foreground = "#b5b5b2"
bright_foreground = "#f5f5f3"

hyprland_active_border = "rgba(f07e06ee) rgba(c9c8c4ee) 45deg"
hyprland_inactive_border = "rgba(736f63aa)"

red = "#c37471"
yellow = "#c9c8c4"
orange = "#c9a68e"
green = "#a9a8a5"
cyan = "#b8b7b3"
blue = "#f07e06"
magenta = "#848482"
brown = "#655347"

bright_red = "#dc9390"
bright_yellow = "#e5e5e3"
bright_green = "#cbcbc9"
bright_cyan = "#d7d7d5"
bright_blue = "#ff9e57"
bright_magenta = "#cacac9"
