mode = "dark"

accent = "#cb74c4"
selection = "#472544"
muted = "#7d607a"

background = "#130612"
dark_background = "#0e050e"
darker_background = "#0a0309"
lighter_background = "#240d22"

foreground = "#d8cad2"
dark_foreground = "#947890"
light_foreground = "#b6a9b1"
bright_foreground = "#f0e9ed"

hyprland_active_border = "rgba(cb74c4ee) rgba(db5c6cee) 45deg"
hyprland_inactive_border = "rgba(7d607aaa)"

red = "#db5c6c"
yellow = "#e6a1c1"
orange = "#e4829e"
green = "#ad8fe9"
cyan = "#a7a6dd"
blue = "#cb74c4"
magenta = "#a773cc"
brown = "#72414f"

bright_red = "#f37d89"
bright_yellow = "#f5b7d3"
bright_green = "#c1a8f9"
bright_cyan = "#bcbbee"
bright_blue = "#e190d9"
bright_magenta = "#c090e2"
