mode = "dark"

accent = "#cf8669"
selection = "#4d3226"
muted = "#82685d"

background = "#1b110c"
dark_background = "#140d09"
darker_background = "#0e0906"
lighter_background = "#2d1c14"

foreground = "#e0d2c3"
dark_foreground = "#998075"
light_foreground = "#bcb1a4"
bright_foreground = "#f7f1e9"

hyprland_active_border = "rgba(cf8669ee) rgba(9ea673ee) 45deg"
hyprland_inactive_border = "rgba(82685daa)"

red = "#c07367"
yellow = "#d2b07b"
orange = "#cf936c"
green = "#9ea673"
cyan = "#95b3c3"
blue = "#cf8669"
magenta = "#bb848f"
brown = "#684a36"

bright_red = "#d38577"
bright_yellow = "#dfbd87"
bright_green = "#adb581"
bright_cyan = "#a2c0d0"
bright_blue = "#e09578"
bright_magenta = "#cc949f"
