mode = "dark"

accent = "#de8251"
selection = "#4e3429"
muted = "#716d7c"

background = "#161519"
dark_background = "#111013"
darker_background = "#0b0b0d"
lighter_background = "#242129"

foreground = "#e6d3c3"
dark_foreground = "#898493"
light_foreground = "#c2b1a3"
bright_foreground = "#fdf2eb"

hyprland_active_border = "rgba(de8251ee) rgba(dc6c7dee) 45deg"
hyprland_inactive_border = "rgba(716d7caa)"

red = "#dc6c7d"
yellow = "#e2b366"
orange = "#eb9065"
green = "#8ab25e"
cyan = "#76c1ad"
blue = "#de8251"
magenta = "#d37ca6"
brown = "#764833"

bright_red = "#f2bcc1"
bright_yellow = "#ecd7b6"
bright_green = "#bcd0ab"
bright_cyan = "#bbdad0"
bright_blue = "#ecc1ab"
bright_magenta = "#e8bed1"
