mode = "light"

accent = "#3a6590"
selection = "#cfd3d9"
muted = "#8c7c72"

background = "#f9f2ee"
dark_background = "#f0e8e3"
darker_background = "#e3dad5"
lighter_background = "#eee2da"

foreground = "#34271f"
dark_foreground = "#726359"
light_foreground = "#50433b"
bright_foreground = "#17100a"

hyprland_active_border = "rgba(3a6590ee) rgba(aa4b3eee) 45deg"
hyprland_inactive_border = "rgba(8c7c72aa)"

red = "#aa4b3e"
yellow = "#6a4f03"
orange = "#8f4b00"
green = "#4e642e"
cyan = "#235f6a"
blue = "#3a6590"
magenta = "#8b5370"
brown = "#482600"

bright_red = "#9e4135"
bright_yellow = "#614801"
bright_green = "#455b25"
bright_cyan = "#1b5763"
bright_blue = "#315c86"
bright_magenta = "#814966"
