mode = "dark"

accent = "#3ba99b"
selection = "#12413c"
muted = "#4b7672"

background = "#021817"
dark_background = "#021211"
darker_background = "#010c0c"
lighter_background = "#002725"

foreground = "#c9d9d2"
dark_foreground = "#658d8a"
light_foreground = "#a8b7b1"
bright_foreground = "#ecf5f2"

hyprland_active_border = "rgba(3ba99bee) rgba(d56f45ee) 45deg"
hyprland_inactive_border = "rgba(4b7672aa)"

red = "#d56f45"
yellow = "#d8b361"
orange = "#dc944a"
green = "#67b78e"
cyan = "#83bebf"
blue = "#3ba99b"
magenta = "#c9817e"
brown = "#6e4a25"

bright_red = "#ed8f69"
bright_yellow = "#eac87f"
bright_green = "#b0d2be"
bright_cyan = "#bfd9d9"
bright_blue = "#a7d1ca"
bright_magenta = "#e09d9a"
