mode = "dark"

accent = "#ac8cae"
selection = "#413141"
muted = "#7a6678"

background = "#170e16"
dark_background = "#110b11"
darker_background = "#0c070b"
lighter_background = "#261925"

foreground = "#d9d0d8"
dark_foreground = "#917e8f"
light_foreground = "#b7aeb5"
bright_foreground = "#f3eef3"

hyprland_active_border = "rgba(ac8caeee) rgba(bc7866ee) 45deg"
hyprland_inactive_border = "rgba(7a6678aa)"

red = "#bc7866"
yellow = "#c8b180"
orange = "#c7966e"
green = "#96a67d"
cyan = "#93b3b8"
blue = "#ac8cae"
magenta = "#8985aa"
brown = "#644b37"

bright_red = "#ce8977"
bright_yellow = "#d5be8d"
bright_green = "#a4b58b"
bright_cyan = "#a0c0c5"
bright_blue = "#bc9bbd"
bright_magenta = "#9a96bb"
