mode = "light"

accent = "#805713"
selection = "#d7ceb8"
muted = "#7f7d6b"

background = "#f0efe7"
dark_background = "#e6e5dc"
darker_background = "#d9d8ce"
lighter_background = "#e2e0d2"

foreground = "#28271e"
dark_foreground = "#666353"
light_foreground = "#45433b"
bright_foreground = "#0c0c06"

hyprland_active_border = "rgba(805713ee) rgba(486542ee) 45deg"
hyprland_inactive_border = "rgba(7f7d6baa)"

red = "#9f4f2e"
yellow = "#62500a"
orange = "#824f0b"
green = "#486542"
cyan = "#3c584d"
blue = "#805713"
magenta = "#8a534f"
brown = "#412806"

bright_red = "#934524"
bright_yellow = "#5b4800"
bright_green = "#415c3a"
bright_cyan = "#355047"
bright_blue = "#764e05"
bright_magenta = "#7f4a46"
