mode = "light"

accent = "#345dbe"
selection = "#c9d5ee"
muted = "#77828f"

background = "#f3f7fc"
dark_background = "#e8edf3"
darker_background = "#dae0e7"
lighter_background = "#e0e9f2"

foreground = "#1b2b4a"
dark_foreground = "#5e6975"
light_foreground = "#384866"
bright_foreground = "#0a1428"

hyprland_active_border = "rgba(345dbeee) rgba(01637fee) 45deg"
hyprland_inactive_border = "rgba(77828faa)"

red = "#ba4137"
yellow = "#3b546f"
orange = "#7a4b87"
green = "#266c3b"
cyan = "#01637f"
blue = "#345dbe"
magenta = "#695da1"
brown = "#3d2644"

bright_red = "#a92d26"
bright_yellow = "#2f4154"
bright_green = "#125e2d"
bright_cyan = "#004d62"
bright_blue = "#2a488d"
bright_magenta = "#4f4779"
