mode = "light"

accent = "#ae3456"
selection = "#ecc6d0"
muted = "#92787d"

background = "#feeff2"
dark_background = "#f6e5e8"
darker_background = "#ead7da"
lighter_background = "#f6dde2"

foreground = "#392328"
dark_foreground = "#775f64"
light_foreground = "#564044"
bright_foreground = "#1b0c10"

hyprland_active_border = "rgba(ae3456ee) rgba(056d60ee) 45deg"
hyprland_inactive_border = "rgba(92787daa)"

red = "#c1303b"
yellow = "#873c00"
orange = "#a53514"
green = "#056d60"
cyan = "#035b5b"
blue = "#ae3456"
magenta = "#a63b7f"
brown = "#531b0a"

bright_red = "#8f292f"
bright_yellow = "#682e04"
bright_green = "#025e52"
bright_cyan = "#024f50"
bright_blue = "#822b42"
bright_magenta = "#7c305f"
