mode = "light"

accent = "#04767d"
selection = "#bdd8dc"
muted = "#76818b"

background = "#f1f4f7"
dark_background = "#e7eaed"
darker_background = "#d9dde1"
lighter_background = "#dfe5ec"

foreground = "#242a32"
dark_foreground = "#5e6771"
light_foreground = "#41474e"
bright_foreground = "#0e1217"

hyprland_active_border = "rgba(cb222cee) rgba(04767dee) 45deg"
hyprland_inactive_border = "rgba(76818baa)"

red = "#cb222c"
yellow = "#923400"
orange = "#ad2d10"
green = "#056667"
cyan = "#025763"
blue = "#04767d"
magenta = "#b73251"
brown = "#571708"

bright_red = "#b6031c"
bright_yellow = "#802c00"
bright_green = "#055859"
bright_cyan = "#004c56"
bright_blue = "#03656a"
bright_magenta = "#a71b42"
