mode = "light"

accent = "#2f6e44"
selection = "#c2d9cc"
muted = "#6e857c"

background = "#ebf7f2"
dark_background = "#e0ede8"
darker_background = "#d1e0da"
lighter_background = "#d6eae2"

foreground = "#182e27"
dark_foreground = "#556b63"
light_foreground = "#364b43"
bright_foreground = "#071511"

hyprland_active_border = "rgba(2f6e44ee) rgba(9d5c2cee) 45deg"
hyprland_inactive_border = "rgba(6e857caa)"

red = "#9d5c2c"
yellow = "#655100"
orange = "#805302"
green = "#48660d"
cyan = "#1b6151"
blue = "#2f6e44"
magenta = "#825a16"
brown = "#402a01"

bright_red = "#8c4b16"
bright_yellow = "#594600"
bright_green = "#3c5800"
bright_cyan = "#035545"
bright_blue = "#1d6036"
bright_magenta = "#734c00"
