mode = "light"

accent = "#a52f87"
selection = "#e9c5de"
muted = "#8f7887"

background = "#fceff7"
dark_background = "#f4e4ee"
darker_background = "#e8d6e1"
lighter_background = "#f4ddeb"

foreground = "#382231"
dark_foreground = "#745f6d"
light_foreground = "#553f4d"
bright_foreground = "#1a0c15"

hyprland_active_border = "rgba(a52f87ee) rgba(2b681bee) 45deg"
hyprland_inactive_border = "rgba(8f7887aa)"

red = "#c03045"
yellow = "#844018"
orange = "#a23925"
green = "#2b681b"
cyan = "#79465b"
blue = "#a52f87"
magenta = "#8c48a0"
brown = "#511d13"

bright_red = "#8f2935"
bright_yellow = "#783406"
bright_green = "#1b5b06"
bright_cyan = "#5b3745"
bright_blue = "#7c2865"
bright_magenta = "#683977"
