mode = "dark"

accent = "#50a38b"
selection = "#163a30"
muted = "#4b7368"

background = "#00110c"
dark_background = "#000d09"
darker_background = "#000906"
lighter_background = "#002018"

foreground = "#d2d0c5"
dark_foreground = "#648a7f"
light_foreground = "#b0afa5"
bright_foreground = "#eeede8"

hyprland_active_border = "rgba(50a38bee) rgba(fba044ee) 45deg"
hyprland_inactive_border = "rgba(4b7368aa)"

red = "#dd614f"
yellow = "#fba044"
orange = "#f28248"
green = "#6cac7a"
cyan = "#75b9b2"
blue = "#50a38b"
magenta = "#d3737c"
brown = "#794124"

bright_red = "#f58270"
bright_yellow = "#febb7f"
bright_green = "#88c394"
bright_cyan = "#90cdc6"
bright_blue = "#72bba4"
bright_magenta = "#e99197"
