mode = "dark"

accent = "#e278a4"
selection = "#552c3c"
muted = "#866470"

background = "#1e0e14"
dark_background = "#170b0f"
darker_background = "#0f070a"
lighter_background = "#311721"

foreground = "#ded1d2"
dark_foreground = "#9d7c88"
light_foreground = "#bbafb0"
bright_foreground = "#f6f0f0"

hyprland_active_border = "rgba(e278a4ee) rgba(86ac72ee) 45deg"
hyprland_inactive_border = "rgba(866470aa)"

red = "#d9616a"
yellow = "#d8b84c"
orange = "#e98d47"
green = "#86ac72"
cyan = "#d6a4aa"
blue = "#e278a4"
magenta = "#c47ab4"
brown = "#754724"

bright_red = "#f3b9b9"
bright_yellow = "#eacc70"
bright_green = "#a0c38e"
bright_cyan = "#e3cbce"
bright_blue = "#ecbacc"
bright_magenta = "#e0bdd7"
