mode = "dark"

accent = "#baa130"
selection = "#423c15"
muted = "#6e7057"

background = "#14150a"
dark_background = "#0f1008"
darker_background = "#0a0b05"
lighter_background = "#212210"

foreground = "#d9d6bf"
dark_foreground = "#86876f"
light_foreground = "#b6b4a0"
bright_foreground = "#f5f3e8"

hyprland_active_border = "rgba(baa130ee) rgba(89a88eee) 45deg"
hyprland_inactive_border = "rgba(6e7057aa)"

red = "#ce6f7c"
yellow = "#d2be44"
orange = "#e79352"
green = "#89a88e"
cyan = "#98bbb0"
blue = "#baa130"
magenta = "#b7904a"
brown = "#744a29"

bright_red = "#e78e99"
bright_yellow = "#e4ddad"
bright_green = "#a3bfa7"
bright_cyan = "#b0cfc6"
bright_blue = "#d3c99d"
bright_magenta = "#d8c6a8"
