mode = "dark"

accent = "#05a3a2"
selection = "#044040"
muted = "#4c7776"

background = "#031a1a"
dark_background = "#021414"
darker_background = "#020d0d"
lighter_background = "#002929"

foreground = "#c8dbd9"
dark_foreground = "#668f8e"
light_foreground = "#a8b9b7"
bright_foreground = "#eef7f6"

hyprland_active_border = "rgba(05a3a2ee) rgba(76cdbaee) 45deg"
hyprland_inactive_border = "rgba(4c7776aa)"

red = "#1a9489"
yellow = "#76cdba"
orange = "#52b4a4"
green = "#3fb1b4"
cyan = "#a4d4d0"
blue = "#05a3a2"
magenta = "#6bbbc6"
brown = "#295a52"

bright_red = "#a8d3cd"
bright_yellow = "#bfe4da"
bright_green = "#a8d3d3"
bright_cyan = "#d6ecea"
bright_blue = "#a4d4d2"
bright_magenta = "#b5d7dc"
