mode = "light"

accent = "#885602"
selection = "#e2d2b5"
muted = "#8a8067"

background = "#fbf5e7"
dark_background = "#f2ebda"
darker_background = "#e6decb"
lighter_background = "#f0e6ce"

foreground = "#322a18"
dark_foreground = "#706651"
light_foreground = "#4e4635"
bright_foreground = "#181308"

hyprland_active_border = "rgba(885602ee) rgba(b14856ee) 45deg"
hyprland_inactive_border = "rgba(8a8067aa)"

red = "#b14856"
yellow = "#644c00"
orange = "#964600"
green = "#3c692b"
cyan = "#615e28"
blue = "#885602"
magenta = "#a84a00"
brown = "#4b2300"

bright_red = "#a03546"
bright_yellow = "#4e3b01"
bright_green = "#2e5c1c"
bright_cyan = "#4b4823"
bright_blue = "#6a4100"
bright_magenta = "#80390a"
