mode = "light"

accent = "#436d70"
selection = "#cdd2cd"
muted = "#867b6a"

background = "#f4efe7"
dark_background = "#ebe5dc"
darker_background = "#dfd8cd"
lighter_background = "#e9e0d1"

foreground = "#2b261e"
dark_foreground = "#6c6253"
light_foreground = "#48433c"
bright_foreground = "#100c08"

hyprland_active_border = "rgba(436d70ee) rgba(3c6352ee) 45deg"
hyprland_inactive_border = "rgba(867b6aaa)"

red = "#925b52"
yellow = "#624f30"
orange = "#795339"
green = "#3c6352"
cyan = "#355452"
blue = "#436d70"
magenta = "#7a5659"
brown = "#3d2a1d"

bright_red = "#865148"
bright_yellow = "#5a4829"
bright_green = "#345a4a"
bright_cyan = "#2f4d4b"
bright_blue = "#396366"
bright_magenta = "#704d50"
