mode = "light"

accent = "#016a7d"
selection = "#b4d7e1"
muted = "#69838f"

background = "#e7f6fd"
dark_background = "#dbedf5"
darker_background = "#cce0e9"
lighter_background = "#d0eaf4"

foreground = "#102d38"
dark_foreground = "#516974"
light_foreground = "#304a54"
bright_foreground = "#03131a"

hyprland_active_border = "rgba(016a7dee) rgba(036a48ee) 45deg"
hyprland_inactive_border = "rgba(69838faa)"

red = "#b83e35"
yellow = "#654f00"
orange = "#8d4b00"
green = "#036a48"
cyan = "#056260"
blue = "#016a7d"
magenta = "#6e53ad"
brown = "#472600"

bright_red = "#a72a24"
bright_yellow = "#584402"
bright_green = "#005b3d"
bright_cyan = "#014c4a"
bright_blue = "#035160"
bright_magenta = "#60449e"
