mode = "light"

accent = "#b73101"
selection = "#eccab9"
muted = "#8c7f6f"

background = "#fbf5ed"
dark_background = "#f2eae2"
darker_background = "#e6ddd3"
lighter_background = "#f1e5d8"

foreground = "#36291a"
dark_foreground = "#726557"
light_foreground = "#524537"
bright_foreground = "#1b1209"

hyprland_active_border = "rgba(b73101ee) rgba(346b27ee) 45deg"
hyprland_inactive_border = "rgba(8c7f6faa)"

red = "#ce2632"
yellow = "#894000"
orange = "#ad3400"
green = "#346b27"
cyan = "#415f47"
blue = "#b73101"
magenta = "#a74470"
brown = "#571a00"

bright_red = "#992529"
bright_yellow = "#6c3100"
bright_green = "#255d16"
bright_cyan = "#35533b"
bright_blue = "#8a2a0e"
bright_magenta = "#7d3655"
