mode = "light"

accent = "#046e6e"
selection = "#b7dad9"
muted = "#6b8684"

background = "#eaf9f7"
dark_background = "#deefee"
darker_background = "#d0e3e1"
lighter_background = "#d3ecea"

foreground = "#162f2e"
dark_foreground = "#536c6a"
light_foreground = "#344c4a"
bright_foreground = "#061615"

hyprland_active_border = "rgba(046e6eee) rgba(014a3fee) 45deg"
hyprland_inactive_border = "rgba(6b8684aa)"

red = "#007e75"
yellow = "#014a3f"
orange = "#025d53"
green = "#055f62"
cyan = "#033a38"
blue = "#046e6e"
magenta = "#00515b"
brown = "#012f2a"

bright_red = "#025f58"
bright_yellow = "#023930"
bright_green = "#004a4d"
bright_cyan = "#062a29"
bright_blue = "#045454"
bright_magenta = "#003f47"
