mode = "light"

accent = "#0e714a"
selection = "#c3dac4"
muted = "#818269"

background = "#f6f7e7"
dark_background = "#eceddb"
darker_background = "#dfe0cc"
lighter_background = "#e7e9cf"

foreground = "#2c2c1a"
dark_foreground = "#676952"
light_foreground = "#484837"
bright_foreground = "#141409"

hyprland_active_border = "rgba(0e714aee) rgba(925f02ee) 45deg"
hyprland_inactive_border = "rgba(818269aa)"

red = "#925f02"
yellow = "#5d5300"
orange = "#765900"
green = "#266b13"
cyan = "#006355"
blue = "#0e714a"
magenta = "#5a6d1e"
brown = "#3b2d00"

bright_red = "#7e5101"
bright_yellow = "#514801"
bright_green = "#175d00"
bright_cyan = "#02564a"
bright_blue = "#02623e"
bright_magenta = "#4c5e03"
