mode = "dark"

accent = "#dd7f55"
selection = "#522f20"
muted = "#83675e"

background = "#1c100c"
dark_background = "#150c09"
darker_background = "#0e0806"
lighter_background = "#2e1b14"

foreground = "#ddd3c5"
dark_foreground = "#9a7f75"
light_foreground = "#bab1a4"
bright_foreground = "#f6f1e9"

hyprland_active_border = "rgba(dd7f55ee) rgba(7cae72ee) 45deg"
hyprland_inactive_border = "rgba(83675eaa)"

red = "#d96453"
yellow = "#e3ac70"
orange = "#e38c5b"
green = "#7cae72"
cyan = "#90b1c8"
blue = "#dd7f55"
magenta = "#cd7c81"
brown = "#72462e"

bright_red = "#f2baaf"
bright_yellow = "#ebd2b7"
bright_green = "#97c58e"
bright_cyan = "#a8c7dd"
bright_blue = "#ebbeaa"
bright_magenta = "#e5bebf"
