mode = "light"

accent = "#984c02"
selection = "#e6cdb9"
muted = "#907b71"

background = "#fcf1ec"
dark_background = "#f3e7e0"
darker_background = "#e7d9d2"
lighter_background = "#f3e0d7"

foreground = "#37251c"
dark_foreground = "#746258"
light_foreground = "#544239"
bright_foreground = "#1a0e08"

hyprland_active_border = "rgba(984c02ee) rgba(665b9fee) 45deg"
hyprland_inactive_border = "rgba(907b71aa)"

red = "#bc3a25"
yellow = "#6d4400"
orange = "#934602"
green = "#446611"
cyan = "#715726"
blue = "#984c02"
magenta = "#665b9f"
brown = "#4a2301"

bright_red = "#8b3020"
bright_yellow = "#543401"
bright_green = "#385801"
bright_cyan = "#564321"
bright_blue = "#763901"
bright_magenta = "#594c90"
