mode = "light"

accent = "#6f5598"
selection = "#d7d0e1"
muted = "#827d8b"

background = "#f4f3f6"
dark_background = "#eae9ed"
darker_background = "#dddbe0"
lighter_background = "#e5e3eb"

foreground = "#2b292f"
dark_foreground = "#686471"
light_foreground = "#48454c"
bright_foreground = "#121115"

hyprland_active_border = "rgba(6f5598ee) rgba(a74470ee) 45deg"
hyprland_inactive_border = "rgba(827d8baa)"

red = "#a74470"
yellow = "#60500b"
orange = "#904722"
green = "#00694f"
cyan = "#006069"
blue = "#6f5598"
magenta = "#8f4a8a"
brown = "#482411"

bright_red = "#7c3655"
bright_yellow = "#493e11"
bright_green = "#01513c"
bright_cyan = "#004a51"
bright_blue = "#534272"
bright_magenta = "#6c3968"
