mode = "light"

accent = "#056989"
selection = "#b8d6e3"
muted = "#6e8291"

background = "#eaf5fd"
dark_background = "#deecf5"
darker_background = "#d0dfe9"
lighter_background = "#d4e8f5"

foreground = "#182c39"
dark_foreground = "#566875"
light_foreground = "#354855"
bright_foreground = "#06121b"

hyprland_active_border = "rgba(056989ee) rgba(7c4500ee) 45deg"
hyprland_inactive_border = "rgba(6e8291aa)"

red = "#b54311"
yellow = "#7c4500"
orange = "#964500"
green = "#006b63"
cyan = "#015d66"
blue = "#056989"
magenta = "#4364a1"
brown = "#4b2300"

bright_red = "#9f3501"
bright_yellow = "#6c3c00"
bright_green = "#00524b"
bright_cyan = "#02484f"
bright_blue = "#02506a"
bright_magenta = "#354c79"
